### ISSUE TITLE
JNI Wrapper

### ISSUE THREAD

**Issue by BlackMesa123** [TGX-Android/tdlib#2]
Hello there,
I've noticed that both this and the [prebuild](https://core.telegram.org/tdlib/tdlib.zip) version of tdlib for Android have a different jni wrapper than the one in the public repo (both [here](https://github.com/tdlib/td/blob/master/example/java/td_jni.cpp) and [here](https://github.com/tdlib/td/issues/77#issuecomment-640719893)). Would it be possible to have a copy of the newer td_jni.cpp?

**Comment by vkryl** [comment]
Since this repo is just a prebuilt version of TDLib, it cannot include `td_jni.cpp` because it's outside of scope of this repository. Kindly request to sync `td_jni.cpp` with the latest used version in [TDLib repository](https://github.com/tdlib/td/issues).

**Comment by BlackMesa123** [comment]
Thanks for you reply. Unfortunately I already asked for it in the TDLib repo ([here](https://github.com/tdlib/td/issues/1992#issuecomment-1142548222)) but I still got no answer today, that's why I asked for the file here, I understand if it can't/won't be shared.
